name: Clean Java Doc

on:
  push:
    branches:
      - javadoc
      
jobs:
  clean:
    name: clean up logic
    runs-on: ubuntu-latest
    steps:
    # checkout out repo and the branch
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: move out
      run: mv ./javadoc/* ./
      
    - name: commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
